language: node_js
node_js:
  - stable
sudo: required
services:
  - docker
before_script:
  - docker pull selenium/standalone-firefox:2.46.0
  - docker pull selenium/standalone-chrome:2.46.0
script:
  - npm test
  - dockers/Screenshotter/screenshotter.sh --verify
